[package]
name = "kbpf-basic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/kbpf-basic"
readme = "README.md"
keywords = ["bpf", "ebpf", "kernel", "tracing", "no-std"]
description = "A no_std Rust eBPF foundation library for kernel or kernel-like environments."

[dependencies]
printf-compat = { version = "0.4", default-features = false }
bitflags = "2"
lru = "0.16"
log = "0.4"
int-enum = "1.2"
axerrno = "0.2"
