[package]
name = "kbpf-basic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["bpf", "ebpf", "kernel", "tracing", "no-std"]
description = "A no_std Rust eBPF foundation library for kernel or kernel-like environments."

[dependencies]
printf-compat = "0.3"
bitflags = "2"
lru = "0.16.3"
log = "0.4"
rbpf = "0.4"
int-enum = "1.2"
axerrno = "0.2"
