[package]
name = "ksym"
authors.workspace = true
version.workspace = true
edition.workspace = true
license-file.workspace = true
readme = "README.md"
keywords = ["kernel", "symbol table", "kallsyms"]
description = "A Rust crate for generating symbol tables for operating systems."

[dependencies]

[features]
assembly = []

[[bin]]
name = "gen_ksym"
