[package]
name = "tp-lexer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["tracepoint", "filter-expression", "lexer", "no-std"]
description = "A Rust crate for no_std filter expression engine for tracepoint-like events in operating systems."

[dependencies]
