use alloc::{string::String, vec::Vec};
use core::{
    ffi::c_void,
    fmt::{self, Write},
    marker::PhantomData,
    sync::atomic::{AtomicU8, Ordering},
};

use static_keys::{RawStaticFalseKey, code_manipulate::CodeManipulator};

pub(crate) const FLAG_PRINT: u8 = 1 << 0;
pub(crate) const FLAG_MODULE: u8 = 1 << 1;
pub(crate) const FLAG_FILE: u8 = 1 << 2;
pub(crate) const FLAG_LINE: u8 = 1 << 3;
pub(crate) const FLAG_THREAD: u8 = 1 << 4;

/// Backend operations used by dynamic debug callsites.
pub trait DebugOps: Send + Sync + 'static {
    /// Patch kernel text for static-key branch updates.
    fn write_kernel_text(addr: *mut u8, data: &[u8]);

    /// Emit the final formatted line.
    fn emit(line: &str);

    /// Return the current thread id used by the `t` prefix flag.
    fn thread_id() -> u64 {
        0
    }
}

/// Runtime metadata for a single `pr_debug!` callsite.
#[repr(C, align(8))]
pub struct DebugSite<K: DebugOps> {
    flags: AtomicU8,
    line: u32,
    module: &'static str,
    file: &'static str,
    function: &'static str,
    format: &'static str,
    key: &'static RawStaticFalseKey<DebugCodeManipulator<K>>,
}

// SAFETY: `DebugSite` is immutable after construction except for its internal
// atomic flags field. The raw key pointer always targets a static key object
// generated by the macro, and the function pointers are immutable code
// addresses. Sharing references to a callsite descriptor is therefore safe.
unsafe impl<K: DebugOps> Sync for DebugSite<K> {}

impl<K: DebugOps> DebugSite<K> {
    /// Construct a new dynamic debug site.
    #[doc(hidden)]
    pub const fn new(
        key: &'static RawStaticFalseKey<DebugCodeManipulator<K>>,
        module: &'static str,
        file: &'static str,
        line: u32,
        function: &'static str,
        format: &'static str,
    ) -> Self {
        Self {
            flags: AtomicU8::new(0),
            line,
            module,
            file,
            function,
            format,
            key,
        }
    }

    /// The source module path for this callsite.
    pub fn module(&self) -> &'static str {
        self.module
    }

    /// The source file path for this callsite.
    pub fn file(&self) -> &'static str {
        self.file
    }

    /// The source function name for this callsite, if captured.
    pub fn function(&self) -> &'static str {
        self.function
    }

    /// The source line for this callsite.
    pub fn line(&self) -> u32 {
        self.line
    }

    /// The original format string literal.
    pub fn format(&self) -> &'static str {
        self.format
    }

    /// The current dynamic debug flags for this callsite.
    pub fn flags(&self) -> u8 {
        self.flags.load(Ordering::Relaxed)
    }

    pub(crate) fn set_flags(&self, next: u8) {
        let prev = self.flags.swap(next, Ordering::Relaxed);
        let prev_print = prev & FLAG_PRINT != 0;
        let next_print = next & FLAG_PRINT != 0;
        if prev_print == next_print {
            return;
        }

        unsafe {
            if next_print {
                self.key.enable();
            } else {
                self.key.disable();
            }
        }
    }

    pub(crate) fn flags_string(&self) -> String {
        flags_to_string(self.flags())
    }
}

impl<K: DebugOps> fmt::Debug for DebugSite<K> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("DebugSite")
            .field("module", &self.module)
            .field("file", &self.file)
            .field("function", &self.function)
            .field("line", &self.line)
            .field("format", &self.format)
            .field("flags", &self.flags())
            .finish()
    }
}

/// Code manipulator used by `static-keys` to patch branch sites.
#[doc(hidden)]
pub struct DebugCodeManipulator<K: DebugOps>(PhantomData<K>);

impl<K: DebugOps> CodeManipulator for DebugCodeManipulator<K> {
    unsafe fn write_code<const L: usize>(addr: *mut c_void, data: &[u8; L]) {
        K::write_kernel_text(addr as _, data);
    }
}

#[doc(hidden)]
pub fn __dynamic_pr_debug<K: DebugOps>(site: &'static DebugSite<K>, args: fmt::Arguments<'_>) {
    let flags = site.flags();
    if flags & FLAG_PRINT == 0 {
        return;
    }

    let mut line = String::new();
    append_prefix::<K>(&mut line, site, flags);
    let _ = write!(line, "{args}");
    if !line.ends_with('\n') {
        line.push('\n');
    }

    K::emit(&line);
}

unsafe extern "C" {
    #[link_name = "__start___dyndbg"]
    static DDEBUG_SITE_START: u8;
    #[link_name = "__stop___dyndbg"]
    static DDEBUG_SITE_STOP: u8;
}

pub(crate) fn scan_debug_sites<K: DebugOps>() -> Vec<&'static DebugSite<K>> {
    let start = (&raw const DDEBUG_SITE_START).cast::<DebugSite<K>>();
    let stop = (&raw const DDEBUG_SITE_STOP).cast::<DebugSite<K>>();
    let len = unsafe { stop.offset_from(start) as usize };
    let raw_sites = unsafe { core::slice::from_raw_parts(start, len) };

    let mut sites = Vec::new();
    for site in raw_sites {
        sites.push(site);
    }
        sites.sort_by(|lhs, rhs| {
            lhs.file()
                .cmp(rhs.file())
                .then(lhs.line().cmp(&rhs.line()))
                .then(lhs.module().cmp(rhs.module()))
                .then(lhs.function().cmp(rhs.function()))
                .then(lhs.format().cmp(rhs.format()))
        });
    sites
}

pub(crate) fn flag_mask_for(chr: char) -> Option<u8> {
    Some(match chr {
        'p' => FLAG_PRINT,
        'm' => FLAG_MODULE,
        'f' => FLAG_FILE,
        'l' => FLAG_LINE,
        't' => FLAG_THREAD,
        _ => return None,
    })
}

fn append_prefix<K: DebugOps>(out: &mut String, site: &DebugSite<K>, flags: u8) {
    if flags & FLAG_THREAD != 0 {
        let _ = write!(out, "tid={} ", K::thread_id());
    }
    if flags & FLAG_MODULE != 0 {
        let _ = write!(out, "[{}] ", site.module());
    }
    if flags & FLAG_FILE != 0 {
        out.push_str(site.file());
        if flags & FLAG_LINE != 0 {
            let _ = write!(out, ":{}", site.line());
        }
        out.push(' ');
    } else if flags & FLAG_LINE != 0 {
        let _ = write!(out, "line:{} ", site.line());
    }
}

fn flags_to_string(flags: u8) -> String {
    let mut out = String::from("=");
    for (bit, chr) in [
        (FLAG_PRINT, 'p'),
        (FLAG_MODULE, 'm'),
        (FLAG_FILE, 'f'),
        (FLAG_LINE, 'l'),
        (FLAG_THREAD, 't'),
    ] {
        if flags & bit != 0 {
            out.push(chr);
        }
    }
    if out.len() == 1 {
        out.push('_');
    }
    out
}
